theme: osuny-hugo-theme-aaa
paginate: 18
enableRobotsTXT: true
removePathAccents: true

params:
  plausible: esee-degrowth2024.uvigo.gal
  breadcrumb:
    position: after-hero
  summary:
    position: hero
  logo:
    footer: "/assets/images/logo-white.svg"